version: 2.1

workflows:
  version: 2
  test:
    jobs:
      - test-node
  build:
    jobs:
      - build-and-push:
          context: 
            - MML harbor
            - dockerhub
      # - deploy:
      #     filters:
      #       branches:
      #         only:
      #           - main

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: node --experimental-vm-modules node_modules/jest/bin/jest.js

  build-and-push:
    working_directory: /app
    resource_class: andrewshomelab/runner-1
    docker:
      - image: gcr.io/kaniko-project/executor:debug
        entrypoint: ""
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: add Docker Hub credentials
          command: |
            mkdir -p /kaniko/.docker
            echo "{
              \"auths\": {
                \"harbor.mymemorylog.com\": {
                  \"auth\": \"$(echo -n $USERNAME:$PASSWORD | base64)\"
                }
              }
            }" > /kaniko/.docker/config.json
            ls
      - run:
          name: Build and Push image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM

            /kaniko/executor \
                --context="/app" \
                --dockerfile="/app/Containerfile" \
                --destination="harbor.mymemorylog.com/cts/cts:$TAG" \
                --ignore-path="/app"
  # deploy: