version: 2.1

orbs:
  node: circleci/node@5

workflows:
  version: 2
  test:
    jobs:
      - test-node:
          
  build:
    jobs:
      - build-and-push:
          context: 
            - MML harbor
            - dockerhub
  deploy:
    jobs:
      - deploy:
          context: 
            - cts-infrastructure
        filters:
          branches:
            only:
              - master

jobs:
  test-node:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: node --experimental-vm-modules node_modules/jest/bin/jest.js

  build-and-push:
    working_directory: /app
    resource_class: andrewshomelab/runner-1
    docker:
      - image: gcr.io/kaniko-project/executor:debug
        entrypoint: ""
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: add Docker Hub credentials
          command: |
            mkdir -p /kaniko/.docker
            echo "{
              \"auths\": {
                \"harbor.mymemorylog.com\": {
                  \"auth\": \"$(echo -n $USERNAME:$PASSWORD | base64)\"
                }
              }
            }" > /kaniko/.docker/config.json
            ls
      - run:
          name: Build and Push image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM

            /kaniko/executor \
                --context="/app" \
                --dockerfile="/app/Containerfile" \
                --destination="harbor.mymemorylog.com/cts/cts:$TAG" \
                --ignore-path="/app"
  deploy:
    docker:
        - image: cimg/base:2023.06
    steps:
      - run:
        name: Update infra repo
        command: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo $CTS_INFRASTRUCTURE_SSH_KEY > ~/.ssh/id_rsa
          git clone git@github.com:Andrew920/cts-infrastructure.git
          cd cts-infrastructure
          git config --global user.email "andraz.marinsek@gmail.com"
          git config --global user.name "CircleCI"
          sed -i "s|image: .*|image: harbor.mymemorylog.com/cts/cts:$TAG|g" gitops/global/deployment.yaml
          git commit -m "CircleCI update image tag to $TAG"
          git push -u origin master